# Generated by Django 4.2.3 on 2023-08-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_references_reference_rename_tags_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='name',
        ),
        migrations.AddField(
            model_name='reference',
            name='link',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
