# Generated by Django 4.2.3 on 2023-08-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_reference_name_reference_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reference',
            name='link',
            field=models.CharField(default=None, max_length=1000, unique=True),
        ),
    ]
